apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: 1st-pvc

spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: myapp
