apiVersion: v1
kind: PersistentVolume

metadata:
  name: 1st-pv
  labels:
    type: 1st-pv

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: 1st-storage-class
  hostPath:
    path: "/mnt/data"